apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: apicurio-tenant-manager
    appstudio.openshift.io/component: apicurio-tenant-manager-akaf
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: apicurio-tenant-manager-akaf
  namespace: nipatil-tenant
spec:
  url: https://github.com/NikishaPatil/apicurio-tenant-manager
