apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-tenant-manager-akaf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-tenant-manager-akaf
    app.kubernetes.io/part-of: apicurio-tenant-manager
  name: apicurio-tenant-manager-akaf
  namespace: nipatil-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: apicurio-tenant-manager-akaf
    weight: 100
status: {}
