apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: apicurio-tenant-manager-akaf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apicurio-tenant-manager-akaf
    app.kubernetes.io/part-of: apicurio-tenant-manager
  name: apicurio-tenant-manager-akaf
  namespace: nipatil-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: apicurio-tenant-manager-akaf
status:
  loadBalancer: {}
